name: build-and-release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write  # required to create a release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      # Linux/macOS: use default toolchains; Windows uses MSVC x64
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package (CPack)
        shell: bash
        run: |
          cd build
          cpack -C Release
          mkdir -p artifacts
          # collect common archive names
          cp ./*.{zip,tgz,tar.gz} artifacts 2>/dev/null || true

      - name: Upload CI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llgml-${{ matrix.os }}
          path: build/artifacts/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
